name = "knights n gears"
author = "yreez"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6341c3b87ec9221ea2ef127e8787d0eb776b4de0d21b2db78502531f7b6666cc"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
